services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.runtime:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['runtime']

  FriendsOfTYPO3\Dashboard\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Dashboard\Controller\DashboardController:
    public: true
  FriendsOfTYPO3\Dashboard\Controller\WidgetAjaxController:
    public: true
  FriendsOfTYPO3\Dashboard\Security\Permission\PermissionAttributeProvider:
    arguments:
      $cache: '@cache.runtime'
    tags:
      -
        name: event.listener
        identifier: 'dashboard-permission-provider'
        event: TYPO3\CMS\Security\Event\AttributeRetrivalEvent