services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Dashboard\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Dashboard\Controller\DashboardController:
    public: true
  FriendsOfTYPO3\Dashboard\Controller\WidgetAjaxController:
    public: true
  FriendsOfTYPO3\Dashboard\Security\AccessControl\Permission\PermissionAttributeProvider:
    arguments:
      - '@cache.runtime'
    tags:
      -
        name: event.listener
        identifier: 'dashboard-permission-provider'
        event: TYPO3\CMS\Security\AccessControl\Event\AttributeRetrivalEvent